### ISSUE TITLE
Bug:"Failed to retrieve records" Snackbar shows every time records update with network

### ISSUE THREAD

**Issue by Babak-gh** [bcgov/myhealthBC-android#528]
### Issue Description:
**Problem**

- While using the application from the Google Play Store, I noticed that a Snackbar is consistently displayed with the message "Failed to retrieve records" every time the app attempts to update records from the server.

**Steps to Reproduce:**

1. Download and install the application from the Google Play Store.
2. Launch the app.
3. Wait until "Retrieving records" Snackbar shown. 
4. Observe the Snackbar message appearing with "Failed to retrieve records."

Or Whenever do a pull to refresh operation in "Records" tab

**Expected Behaviour:**

- The Snackbar with the message "Failed to retrieve records" should not be displayed during record update operations as most of the records are fetching without problem. Users do not expect to see a Failed message on every records update.

**Actual Behavior:**

- The Snackbar is displayed even during successful record updates, leading to confusion.

**Additional Information:**

- Apparently the problem is `qrCode` and `federalVaccineProof` fields are non-nullable in `VaccineResourcePayload` data class but these fields are `null` in data returns from network when user does not have any vaccine records.
- I cloned the source code from the repository and tested the "develop" branch using the "prodDebug" build variant.
- The issue persists in the codebase of the "develop" branch.
- I have identified the problem in the code and created a fix.
- I have opened a [pull request](https://github.com/bcgov/myhealthBC-android/pull/527) with the proposed fix.

**Proposed Solution:**

- I have fixed the issue by making `qrCode` and `federalVaccineProof` fields nullable and then handle the `null` data in `processResponse` method in `FetchVaccineRecordRepository` class. Leads to avoiding `NullPointerExceptions` from occurring in the `FetchAuthenticatedHealthRecordsWorker` worker process.
- My [pull request ](https://github.com/bcgov/myhealthBC-android/pull/527) contains the code changes necessary to address this problem.

**Comment by PINAKIN-KANSARA-EY** [comment]
Thanks @Babak-gh , we have taken your feedback and it is resolved in latest version of the app.

**Comment by Babak-gh** [comment]
Thanks @PINAKIN-KANSARA-EY, I'm glad my report helped improve the app's functionality. Since I've also opened a pull request, I'm curious: are you open to open source contributions from outside contributors like myself? I'd love to contribute further if there's an opportunity to do so. Thanks again for your attention to this matter.
